import { useState, useEffect, useCallback, useRef } from "react";
import {
  Search, BookOpen, FileText, ChefHat, Users, Settings,
  Home, ArrowLeft, Plus, Edit3, Trash2, LogIn, LogOut,
  MapPin, Clock, Tag, X, ChevronRight, Lock, Save,
  AlertTriangle, Star, Menu, Eye, Hash
} from "lucide-react";
import { db, storage } from './firebase.js';
import { collection, doc, getDocs, setDoc, deleteDoc, onSnapshot, writeBatch } from 'firebase/firestore';
import { ref, uploadBytes, getDownloadURL, deleteObject } from 'firebase/storage';

const ADMIN_PASSWORD = "AlifeHG2026";
const RECIPE_PASSWORD = "AlifeKitchen2026";

const CATEGORIES = [
  { id: "sops", label: "SOPs", icon: FileText, color: "#C8952A", desc: "Standard Operating Procedures" },
  { id: "training", label: "Training", icon: BookOpen, color: "#4A90D9", desc: "Training Programs & Guides" },
  { id: "recipes", label: "Recipes", icon: ChefHat, color: "#5CB85C", desc: "Kitchen Recipes & Specs" },
  { id: "hr", label: "HR & Policies", icon: Users, color: "#9B59B6", desc: "People Policies & Benefits" },
  { id: "operations", label: "Operations", icon: Settings, color: "#E67E22", desc: "Ops Procedures & Checklists" },
  { id: "quickref", label: "Quick Reference", icon: Star, color: "#E74C3C", desc: "Fast Answers & Key Info" },
];

const LOCATIONS = ["All Locations","Bungalow","FRNDS","Kamp Houston","Lost & Found","Prospect Park","Stick Talk Midtown","Stick Talk Royal Oaks"];
const ROLES = ["All Staff", "Front of House", "Back of House", "Bar", "Management"];

const SEED_DOCS = [
  {id:"s1",title:"Allergen Awareness & Guest Response",category:"sops",subcategory:"Food Safety",content:`# Allergen Awareness & Guest Response SOP\n\n## Purpose\nEnsure all staff are equipped to handle guest allergen inquiries safely and prevent allergic reactions at all Alife concepts.\n\n## The Big 9 Allergens (FDA 2023)\n- Milk\n- Eggs\n- Fish\n- Shellfish / Crustacean\n- Tree Nuts\n- Peanuts\n- Wheat\n- Soybeans\n- Sesame\n\n## Guest Interaction Protocol\nWhen a guest discloses an allergy:\n1. Stop and give them your FULL attention \u2014 treat every allergy as life-threatening.\n2. NEVER guess. Check with the kitchen directly.\n3. Reference the allergen binder at the host stand.\n4. Flag the ticket with an ALLERGY sticker AND communicate verbally to expo and cook.\n5. A manager must be notified for every allergy ticket.\n\n## Cross-Contamination Prevention\n- Use dedicated allergen-safe prep surfaces (marked with red tape).\n- Change gloves before preparing an allergen-sensitive dish.\n- Use clean, separate utensils \u2014 never reuse from another station.\n- Communicate the allergy through every handoff: server \u2192 expo \u2192 cook.\n\n## Incident Response\nIf a guest has a reaction:\n1. Call 911 immediately.\n2. Notify the manager on duty.\n3. Do NOT move or attempt to medicate the guest.\n4. Preserve all food items involved.\n5. Complete an Incident Report Form within 1 hour of the incident.\n\n## Consequences of Non-Compliance\nFailure to follow this SOP is grounds for immediate termination. Guest safety is non-negotiable.`,tags:["allergen","food safety","guest safety","incident","big 9"],locations:["All Locations"],roles:["All Staff"],featured:true,lastUpdated:"2025-03-01",createdBy:"Alife Management"},
  {id:"s2",title:"Incident Report & Response Protocol",category:"sops",subcategory:"Safety & Incidents",content:`# Incident Report & Response Protocol\n\n## When to File a Report\nFile an Incident Report Form within 1 hour any time the following occurs:\n- Guest injury on premises (slips, falls, cuts, burns)\n- Staff injury during a shift\n- Allergic reaction or foodborne illness complaint\n- Property damage caused by staff or guest\n- Altercation or removal of a guest\n- Theft or suspected theft\n\n## Immediate Response Steps\n1. **Ensure safety first.** If someone is hurt, call 911 before anything else.\n2. **Notify the Manager on Duty immediately** \u2014 do not handle alone.\n3. **Do not move, clean, or alter the scene** until the manager assesses.\n4. **Preserve evidence** \u2014 photograph if safe and appropriate.\n5. **Gather witness information** \u2014 names and contact info of any witnesses.\n\n## Completing the Incident Report\nReports are located at the manager\u2019s station. Complete every field \u2014 incomplete reports are not accepted.\n\nRequired fields:\n- Date, time, and exact location of incident\n- Full name of person(s) involved\n- Step-by-step account of what happened\n- Names of all staff witnesses\n- Actions taken at time of incident\n- Manager on duty signature\n\n## After the Report\n- Fax/email completed report to the Alife operations team within 24 hours.\n- Manager retains a copy at the location for 90 days.\n- For guest injuries, alert Alife management immediately \u2014 do not make any promises or admissions to the guest.\n\n## Confidentiality\nAll incident reports are confidential. Do not discuss the incident with other staff or post anything on social media.`,tags:["incident","injury","report","safety","SOP"],locations:["All Locations"],roles:["Management","All Staff"],featured:true,lastUpdated:"2025-03-05",createdBy:"Alife Management"},
  {id:"s3",title:"Cash Handling & End-of-Night Checkout",category:"sops",subcategory:"Financial Controls",content:`# Cash Handling & End-of-Night Checkout\n\n## Purpose\nStandardize cash handling to prevent discrepancies, theft, and accounting errors across all Alife locations.\n\n## Opening the Drawer\n1. Manager counts the opening bank at start of shift with a second witness.\n2. Record the opening count on the Cash Drawer Log.\n3. Both manager and witness initial the log.\n\n## During Service\n- Only one person per register at a time \u2014 no sharing drawers.\n- If a register shows a discrepancy during service, notify the MOD immediately.\n- No personal items in or near the cash drawer \u2014 ever.\n- All voids and comps must be approved by a manager and logged in Toast.\n\n## End-of-Night Checkout (Servers)\n1. Print your individual checkout report from Toast.\n2. Count your cash collected, deduct your opening bank, and reconcile against your report.\n3. Place the counted cash, your report, and credit card slips in a signed envelope.\n4. Turn in the envelope to the Manager on Duty. Both parties count and sign off.\n\n## End-of-Night Checkout (Manager)\n1. Close out all checks in Toast for the night.\n2. Run the Daily Sales Summary report.\n3. Count the drawer \u2014 document the closing count on the Cash Drawer Log.\n4. Calculate the over/short amount. Anything over $5 variance must be reported to ownership.\n5. Prepare the bank deposit \u2014 double-count, bag it, seal it, and log it.\n6. Deposit in the safe or take directly to the bank per location protocol.\n\n## Discrepancy Protocol\n- Variances $1\u2013$5: Note on log and monitor for patterns.\n- Variances $5\u2013$20: Written incident report required.\n- Variances $20+: Automatic investigation. Staff may be suspended pending review.\n- Repeated small variances: Grounds for corrective action.`,tags:["cash","checkout","register","money","POS","financial"],locations:["All Locations"],roles:["Front of House","Bar","Management"],featured:false,lastUpdated:"2025-02-10",createdBy:"Alife Management"},
  {id:"s4",title:"Guest Complaint Resolution",category:"sops",subcategory:"Guest Experience",content:`# Guest Complaint Resolution SOP\n\n## Purpose\nEvery complaint is an opportunity to turn a frustrated guest into a loyal one. This SOP standardizes how we handle complaints at all Alife concepts.\n\n## The L.A.S.T. Method\nAll staff should follow this framework:\n\n**L \u2014 Listen**\nLet the guest speak without interrupting. Make eye contact. Do not get defensive.\n\n**A \u2014 Apologize**\nOffer a sincere apology: \u201CI\u2019m sorry that happened \u2014 that\u2019s not the experience we want for you.\u201D\n\n**S \u2014 Solve**\nFix the problem immediately if you can. If it requires a manager, get one without delay.\n\n**T \u2014 Thank**\nThank the guest for telling you. \u201CThank you for letting us know \u2014 we want to make this right.\u201D\n\n## Authority Levels\n- **Servers/Bartenders:** May re-fire a dish, offer a replacement, or remove an item from the check.\n- **Shift Leads:** May comp up to 1 entr\u00e9e or offer a round of drinks.\n- **Managers/GMs:** May comp an entire check, offer gift cards, or arrange a follow-up gesture.\n- **Ownership:** Contact for any complaint involving injury, social media threats, or legal mentions.\n\n## Escalation Triggers \u2014 Get a Manager Immediately\n- Guest mentions a lawyer, lawsuit, or health department.\n- Guest appears to be recording the interaction.\n- Guest had an allergic reaction (follow Allergen SOP simultaneously).\n- Any physical altercation or safety threat.\n- Guest demands to speak with ownership.\n\n## After the Interaction\n- Log the complaint in the Manager Shift Log with full details.\n- If the guest left contact information, a manager follows up within 24 hours.\n- Identify the root cause \u2014 was it a training issue, a kitchen mistake, or a systems failure?\n- Use complaints as training examples during pre-shift meetings (no names).`,tags:["complaint","guest","resolution","service recovery","LAST"],locations:["All Locations"],roles:["All Staff"],featured:false,lastUpdated:"2025-02-18",createdBy:"Alife Management"},
  {id:"s5",title:"TABC Compliance & Responsible Alcohol Service",category:"sops",subcategory:"Alcohol Service",content:`# TABC Compliance & Responsible Alcohol Service\n\n## Purpose\nAll Alife staff who serve, sell, or handle alcoholic beverages must maintain active TABC certification and follow Texas alcohol regulations at all times.\n\n## Certification Requirements\n- **TABC Seller-Server Certificate** is required before your first shift serving alcohol.\n- Certification must be completed through a TABC-approved provider.\n- Certificates are valid for 2 years from date of completion.\n- A copy must be on file at your location and with Alife HR.\n\n## ID Checking Protocol\n1. Check ID for **every guest** who appears under 40 years of age.\n2. Acceptable IDs: State-issued driver\u2019s license, state ID, US passport, military ID.\n3. Check for: Photo match, expiration date, birth date (must be 21+), signs of tampering.\n4. If the ID is expired, damaged, or suspicious \u2014 refuse service and notify a manager.\n5. **Never accept** screenshots of IDs, international driver\u2019s licenses without a passport, or student IDs.\n\n## Signs of Intoxication (Cut-Off Protocol)\nWatch for these indicators:\n- Slurred speech, loss of balance, or impaired coordination\n- Loud or aggressive behavior escalation\n- Difficulty focusing eyes or drooping eyelids\n- Slow response to questions\n\nWhen you identify intoxication:\n1. Stop alcohol service to the guest immediately \u2014 you are legally required to.\n2. Offer water, coffee, or food.\n3. Notify the Manager on Duty.\n4. Do NOT let the intoxicated guest drive. Offer to call a ride.\n5. Document the situation in the Shift Log.\n\n## Legal Liability\nServing an intoxicated person or a minor is a **Class A misdemeanor** in Texas, punishable by fines up to $4,000 and jail time. Alife and the individual server can both be held liable.\n\n## Consequences\nFailure to check IDs or serving a visibly intoxicated guest is grounds for immediate termination.`,tags:["TABC","alcohol","ID check","intoxication","compliance","legal"],locations:["All Locations"],roles:["Front of House","Bar","Management"],featured:true,lastUpdated:"2025-01-25",createdBy:"Alife Management"},
  {id:"s6",title:"To-Go & Delivery Order Procedures",category:"sops",subcategory:"Order Handling",content:`# To-Go & Delivery Order Procedures\n\n## Purpose\nEnsure every to-go and delivery order leaves our kitchen correct, complete, and on time. Errors on to-go orders cost us the most \u2014 we can\u2019t fix them once they leave the building.\n\n## Order Entry\n1. All to-go orders are entered through Toast \u2014 never handwritten tickets.\n2. Double-check modifiers, allergies, and special requests before sending to the kitchen.\n3. If the guest has an allergy, flag it with an ALLERGY sticker on the bag AND the container.\n\n## Packing Checklist (Every Order)\n- [ ] Correct items vs. the ticket \u2014 check every container\n- [ ] Correct sides and sauces\n- [ ] Utensils, napkins, and condiments included\n- [ ] Allergy items separated and labeled if applicable\n- [ ] Receipt stapled to the bag\n- [ ] Bag sealed (staple or sticker)\n\n## Quality Control\n- **Expo or Manager must verify** every to-go order against the ticket before it leaves.\n- If an item looks wrong, re-fire it. Do not send food that doesn\u2019t meet standards.\n- Hot food and cold food must be packed separately.\n\n## Delivery Partner Orders (DoorDash, UberEats)\n- Confirm the order number with the driver.\n- Hand the order directly to the driver \u2014 do not leave it unattended.\n- If a driver is late (15+ minutes for hot food), notify MOD for quality assessment.\n\n## Key Reminder\nThe Prospect Park protein mix-up incident is exactly why this process exists. Every container must be verified. There are no shortcuts.`,tags:["to-go","delivery","doordash","uber eats","packing","order"],locations:["All Locations"],roles:["All Staff"],featured:false,lastUpdated:"2025-03-12",createdBy:"Alife Management"},
  {id:"s7",title:"New Employee Onboarding Overview",category:"training",subcategory:"Onboarding",content:`# New Employee Onboarding Overview\n\n## Welcome to Alife Hospitality Group\nYou\u2019re joining a team that operates 7 unique concepts across Houston \u2014 Bungalow, FRNDS, Kamp Houston, Lost & Found, Prospect Park, Stick Talk Midtown, and Stick Talk Royal Oaks. This guide covers your first two weeks.\n\n## Week 1 \u2014 Orientation\n**Day 1:** HR paperwork, handbook review, facility tour, uniform fitting\n**Day 2:** Food safety certification and allergen training (required before first service shift)\n**Day 3\u20134:** Shadowing in your department (FOH, BOH, or Bar)\n**Day 5:** POS training on Toast and hands-on practice with a trainer\n\n## Week 2 \u2014 Role-Specific Training\n- Work alongside your assigned trainer for full shifts\n- Complete all required knowledge checks with a passing score of 80%+\n- Review all SOPs relevant to your role in this portal\n- Learn scheduling system and how to request time off\n\n## Required Certifications\nAll certifications must be completed within 30 days of hire:\n- **Texas Food Handler Certificate** \u2014 all staff\n- **TABC Certification** \u2014 all alcohol-serving staff\n- **Allergen Awareness Sign-Off** \u2014 all staff (Day 2 of onboarding)\n\n## Key Contacts\n- Schedule questions \u2192 Your location\u2019s GM\n- HR questions \u2192 Your direct manager\n- Payroll issues \u2192 Contact the Alife operations team\n- Tech issues (Toast, etc.) \u2192 Manager on Duty\n\n## Important Reminder\nThis training portal is your go-to resource. Bookmark it. Search before you ask \u2014 the answer is usually here.`,tags:["onboarding","new hire","orientation","week 1","training"],locations:["All Locations"],roles:["All Staff"],featured:true,lastUpdated:"2025-01-10",createdBy:"Alife Management"},
  {id:"s8",title:"Steps of Service \u2014 Full Service Concepts",category:"training",subcategory:"Service Standards",content:`# Steps of Service \u2014 Full Service Concepts\n\n## The Alife Standard\nEvery guest interaction should feel intentional, warm, and effortless. These steps are your blueprint \u2014 master them, then make them your own.\n\n## 10 Steps of Service\n\n**Step 1 \u2014 The Welcome (within 60 seconds of seating)**\nGreet the table with eye contact and a genuine smile. Introduce yourself by name.\n\n**Step 2 \u2014 First Beverage Order**\nOffer cocktails, wine, or a specialty drink first. Make one recommendation with confidence.\n\n**Step 3 \u2014 Menu Knowledge Drop**\nShare one featured item or special with genuine enthusiasm. Guests buy what their server is excited about.\n\n**Step 4 \u2014 Take the Food Order**\nRepeat the order back. Note any allergies \u2014 if mentioned, follow the Allergen SOP immediately.\n\n**Step 5 \u2014 Beverage Maintenance**\nNever let a glass hit empty. Check beverages every 5\u20137 minutes without being asked.\n\n**Step 6 \u2014 Food Delivery**\nDeliver food hot and correctly. Confirm every guest is satisfied within 2 minutes of delivery (the 2-Minute Check).\n\n**Step 7 \u2014 Mid-Meal Check**\n\u201CIs there anything I can bring you?\u201D \u2014 Ask, don\u2019t hover.\n\n**Step 8 \u2014 Dessert & Digestif Offer**\nAlways offer dessert and an after-dinner drink. This is easy revenue \u2014 don\u2019t skip it.\n\n**Step 9 \u2014 The Check**\nDeliver the check promptly once they signal readiness. Thank them for coming in \u2014 mean it.\n\n**Step 10 \u2014 The Goodbye**\nSee your guests out if possible. A warm farewell creates a return visit.\n\n## The Cardinal Rules\n- Never say \u201CNo problem\u201D \u2014 say \u201CAbsolutely\u201D or \u201COf course.\u201D\n- Never complain to a table about the kitchen or the team.\n- Own every mistake. Apologize, fix it, inform your manager.`,tags:["steps of service","FOH","service standards","training","guest experience"],locations:["All Locations"],roles:["Front of House","Management"],featured:false,lastUpdated:"2025-02-20",createdBy:"Alife Management"},
  {id:"s9",title:"BOH 7-Day Retraining & Recertification Program",category:"training",subcategory:"Kitchen Training",content:`# BOH 7-Day Retraining & Recertification Program\n\n## Purpose\nA structured 7-day retraining program for all BOH staff \u2014 managers, chefs, and line cooks \u2014 designed to reset standards, reinforce consistency, and recertify on core execution.\n\n## Program Structure\n\n### Day 1 \u2014 Food Safety Reset\n- Temperature danger zones, FIFO rotation, cooling & reheating standards\n- Allergen cross-contamination prevention (hands-on drill)\n- Sanitation station audit and sanitizer concentration testing\n- Knowledge check: 80% minimum to pass\n\n### Day 2 \u2014 Knife Skills & Mise en Place\n- Knife grip, cuts (brunoise, julienne, chiffonade, bias), and safety\n- Station setup standards: labeled containers, portioned mise, clean rail\n- Speed drill: Prep 5 menu items to spec within 20 minutes\n\n### Day 3 \u2014 Protein Cooking Standards\n- Temperature targets for every protein on the menu\n- Whole-cook method: cook whole, rest, slice at plating to 6oz cooked weight\n- Garlic butter staging: 3 additions during cook (sear, mid-cook, finish)\n- Marination windows: 24hr beef/chicken/salmon, 18hr max shrimp/crawfish\n\n### Day 4 \u2014 Sauce & Seasoning Mastery\n- Batch-prep all proprietary sauces and seasonings to recipe spec\n- QC check: color, aroma, taste, and consistency for every batch\n- Blind taste test vs. competitor benchmarks\n\n### Day 5 \u2014 Plate Specs & Plating Drill\n- Standard hibachi plate clock: protein at 12, rice at 6, veggies at 10\n- Portion accuracy drill (scale check every plate)\n- Speed + quality: 6 plates in 8 minutes, all to spec\n\n### Day 6 \u2014 Line Simulation\n- Full mock service: tickets fired, timed, and graded by expo\n- Communication drill: call-backs, all-day counts, fire calls\n- Debrief and coaching after each round\n\n### Day 7 \u2014 Final Exam & Certification\n- Written knowledge check (food safety, recipes, procedures) \u2014 80% to pass\n- Practical cooking exam: 3 dishes prepared to full spec under timed conditions\n- Signed off by GM or Exec Chef\n- Certification valid for 12 months\n\n## Failure to Certify\nStaff who do not pass by the end of Day 7 receive one additional attempt. Continued failure may result in reassignment or separation.`,tags:["retraining","BOH","certification","kitchen","7-day","training program"],locations:["All Locations"],roles:["Back of House","Management"],featured:true,lastUpdated:"2025-03-08",createdBy:"Alife Management"},
  {id:"s10",title:"Prospect Park \u2014 Kitchen Retraining Gameplan",category:"training",subcategory:"Kitchen Training",content:`# Prospect Park \u2014 Kitchen Retraining Gameplan\n\n## Overview\nClosed-day retraining session covering 16 menu items across 8 cooks. This gameplan ensures every cook at Prospect Park can execute every dish to spec from memory under service pressure.\n\n## Format\n- **Duration:** Full closed day (8 hours)\n- **Team:** 8 cooks, rotating through 2 stations\n- **Method:** Demonstrate \u2192 Practice \u2192 Test at each station\n- **Language:** English primary. Spanish translation available for all materials for Spanish-first team members.\n\n## Station Rotation Schedule\nEach cook rotates through both stations. 2 hours per station, 4 items per station.\n\n**Station A \u2014 Grill & Saut\u00e9 (Items 1\u20138)**\nCovers all grilled proteins, saut\u00e9ed dishes, and sauce finishing. Focus: internal temps, resting times, sauce portioning, and plate clock.\n\n**Station B \u2014 Fry, Prep & Assembly (Items 9\u201316)**\nCovers all fried items, cold prep, and assembly-heavy plates. Focus: oil temp, breading process, portion accuracy, and timing.\n\n## Testing Protocol\n- Each cook must plate each of their 16 items once under timed conditions.\n- Expo (GM or Sous Chef) grades each plate: Pass / Redo.\n- All 16 items must pass to complete certification.\n\n## Materials Required\n- Printed Batch Prep Recipes for all 16 items\n- Printed Line Cards at each station\n- Printed Plate Spec sheets with clock diagrams at expo\n- Digital scale at each station\n- Spanish-translated versions of all materials for Spanish-first cooks\n\n## Post-Training\n- Certified cooks are listed on the Certification Tracker posted in the kitchen.\n- Any cook not certified by end of day enters a 3-day remediation period.\n- GM follows up with ownership on results within 24 hours.`,tags:["prospect park","retraining","16 items","closed day","kitchen","certification"],locations:["Prospect Park"],roles:["Back of House","Management"],featured:false,lastUpdated:"2025-03-15",createdBy:"Alife Management"},
  {id:"s11",title:"Food Handler Certification Requirements",category:"training",subcategory:"Certifications",content:`# Food Handler Certification Requirements\n\n## Overview\nThe State of Texas requires all food service employees to obtain a Food Handler Certificate within 60 days of employment. Alife Hospitality Group requires certification within 30 days of hire \u2014 no exceptions.\n\n## How to Get Certified\n1. Complete a DSHS-approved Food Handler training program (online or in-person).\n2. Pass the exam with a minimum score of 70%.\n3. Print or download your certificate.\n4. Submit a copy to your General Manager within 30 days of hire.\n\n## Approved Providers\n- **StateFoodSafety.com** \u2014 Online, ~2 hours, available in English and Spanish.\n- **ServSafe** \u2014 Online or in-person, recognized nationwide.\n- **360Training** \u2014 Online, Texas-specific program.\n\n## Cost\nAlife will reimburse the cost of the Food Handler Certificate upon successful completion. Submit your receipt and certificate together to your GM.\n\n## Renewal\n- Texas Food Handler Certificates are valid for **2 years**.\n- It is your responsibility to renew on time. Expired certifications = no kitchen shifts until renewed.`,tags:["food handler","certification","Texas","DSHS","training"],locations:["All Locations"],roles:["All Staff"],featured:false,lastUpdated:"2025-01-15",createdBy:"Alife Management"},
  {id:"s12",title:"Master Cajun Hibachi Seasoning \u2014 Batch Recipe",category:"recipes",subcategory:"Seasonings & Sauces",content:`# Master Cajun Hibachi Seasoning \u2014 Batch Recipe\n\n## Yield: Full Batch (~2 lbs)\n**Concept:** Stick Talk Midtown & Royal Oaks\n**Classification:** PROPRIETARY \u2014 Do not share outside Alife team\n\n## Ingredients (Full Batch)\n- Smoked Paprika \u2014 6 oz\n- Cayenne Pepper \u2014 1.5 oz\n- Garlic Powder \u2014 4 oz\n- Onion Powder \u2014 3 oz\n- Dried Oregano \u2014 1.5 oz\n- Dried Thyme \u2014 1 oz\n- White Pepper \u2014 1 oz\n- Black Pepper \u2014 1.5 oz\n- Kosher Salt \u2014 4 oz\n- Celery Salt \u2014 1 oz\n\n## Method\n1. Weigh each ingredient on a digital scale \u2014 volume measurement is not acceptable.\n2. Combine all ingredients in a large stainless mixing bowl.\n3. Whisk thoroughly for 90 seconds until fully integrated and color is uniform.\n4. Transfer to labeled airtight containers.\n5. Label: SEASONING NAME / DATE MADE / MADE BY / USE BY (30 days)\n\n## QC Check\n- Color: Deep rust-red with visible herb flecks\n- Aroma: Bold smoke, heat, garlic forward\n- No clumping \u2014 if clumping present, discard and remake\n\n## Usage Notes\n- Standard application: 1.5 tsp per 6 oz protein\n- For bold coating: 2 tsp per 6 oz\n- Never apply to raw protein in advance \u2014 season at station immediately before cooking\n\n## Storage\nCool, dry location. Away from heat and steam. Discard after 30 days.`,tags:["recipe","seasoning","cajun","hibachi","stick talk","proprietary"],locations:["Stick Talk Midtown","Stick Talk Royal Oaks"],roles:["Back of House","Management"],featured:true,lastUpdated:"2025-03-10",createdBy:"Alife Management"},
  {id:"s13",title:"Garlic Miso Butter \u2014 Batch Recipe",category:"recipes",subcategory:"Seasonings & Sauces",content:`# Garlic Miso Butter \u2014 Batch Recipe\n\n## Yield: Full Batch (~3 lbs compound butter)\n**Concept:** Stick Talk Midtown & Royal Oaks\n**Classification:** PROPRIETARY \u2014 Do not share outside Alife team\n\n## Ingredients (Full Batch)\n- Unsalted Butter (room temp) \u2014 2 lbs\n- White Miso Paste \u2014 6 oz\n- Fresh Garlic, minced \u2014 3 oz\n- Toasted Sesame Oil \u2014 1 oz\n- Soy Sauce \u2014 1 oz\n- Rice Vinegar \u2014 0.5 oz\n- Fresh Ginger, microplaned \u2014 0.5 oz\n- Black Pepper \u2014 0.25 oz\n- Scallion Greens, finely sliced \u2014 1 oz (fold in last)\n\n## Method\n1. Butter must be fully room temperature \u2014 do not microwave.\n2. In a large mixing bowl, combine butter and miso paste. Mix with a rubber spatula until fully incorporated (2\u20133 minutes).\n3. Add garlic, sesame oil, soy sauce, rice vinegar, ginger, and black pepper. Mix until uniform.\n4. Fold in scallion greens gently \u2014 do not overmix.\n5. Transfer to labeled deli containers.\n6. Label: GARLIC MISO BUTTER / DATE MADE / MADE BY / USE BY (7 days refrigerated)\n\n## QC Check\n- Color: Golden with visible green scallion flecks\n- Aroma: Rich garlic, savory umami, hint of sesame\n- Texture: Smooth and spreadable, no butter lumps\n- Taste: Bold savory with layered depth \u2014 should hit a \u201Cwow\u201D on the first taste\n\n## Usage \u2014 3-Stage Garlic Butter Application\nThis butter is applied in 3 stages during hibachi cooking:\n1. **Sear stage** \u2014 1 tbsp on the flat top before protein goes down\n2. **Mid-cook stage** \u2014 1 tsp melted over the protein during the flip\n3. **Finish stage** \u2014 1 tsp brushed on the protein at plating\n\n## Storage\nRefrigerated, sealed, 7-day max shelf life. Discard if any off-odors develop.`,tags:["recipe","garlic miso butter","compound butter","stick talk","hibachi","proprietary"],locations:["Stick Talk Midtown","Stick Talk Royal Oaks"],roles:["Back of House","Management"],featured:true,lastUpdated:"2025-03-10",createdBy:"Alife Management"},
  {id:"s14",title:"Stick Talk \u2014 Protein Cooking Standards",category:"recipes",subcategory:"Cooking Standards",content:`# Stick Talk \u2014 Protein Cooking Standards\n\n## The Whole-Cook Method\nAll Stick Talk proteins are cooked WHOLE and sliced at plating. This ensures even seasoning, juicier results, and consistent 6 oz cooked portions.\n\n## Protein Specifications\n\n### Steak (Ribeye)\n- **Raw weight:** 8 oz \u2192 **Cooked target:** 6 oz\n- **Internal temp:** 135\u00b0F (medium) default\n- **Marination window:** 24 hours\n- **Cook method:** Flat top, high heat. Garlic butter staged in 3 additions.\n- **Rest:** 3 minutes before slicing. Slice against the grain, fan on plate at 12 o\u2019clock.\n\n### Chicken Breast\n- **Raw weight:** 8 oz \u2192 **Cooked target:** 6 oz\n- **Internal temp:** 165\u00b0F \u2014 non-negotiable\n- **Marination window:** 24 hours\n- **Cook method:** Flat top, medium-high. Garlic butter at all 3 stages.\n- **Slice:** Bias cut, 5\u20136 slices, fanned at 12 o\u2019clock.\n\n### Salmon\n- **Raw weight:** 7 oz \u2192 **Cooked target:** 6 oz\n- **Internal temp:** 145\u00b0F\n- **Marination window:** 24 hours\n- **Cook method:** Skin-side down 70% of cook time, flip to finish. Garlic butter at sear and finish only.\n- **Plate:** Skin-side up at 12 o\u2019clock. Do not slice.\n\n### Shrimp\n- **Raw weight:** 8 oz (~8\u201310 pieces) \u2192 **Cooked target:** 6 oz\n- **Internal temp:** 145\u00b0F\n- **Marination window:** 18 hours MAX\n- **Cook method:** High heat, 90 seconds per side. Garlic butter at sear stage only.\n\n### Crawfish\n- **Raw weight:** 8 oz \u2192 **Cooked target:** 6 oz\n- **Internal temp:** 145\u00b0F\n- **Marination window:** 18 hours MAX (hard limit)\n- **Cook method:** High heat, toss frequently. Garlic butter at sear stage.\n\n## Standard Hibachi Plate Clock\n- **12 o\u2019clock:** Protein\n- **6 o\u2019clock:** Fried rice\n- **10 o\u2019clock:** Saut\u00e9ed vegetables\n\n## Non-Negotiables\n- NEVER serve undercooked chicken. 165\u00b0F every time.\n- NEVER exceed marination windows \u2014 shrimp/crawfish degrade rapidly past 18 hours.\n- EVERY plate gets weighed during training. During service, spot-checked by expo.`,tags:["protein","cooking standards","steak","chicken","salmon","shrimp","crawfish","stick talk","temperatures"],locations:["Stick Talk Midtown","Stick Talk Royal Oaks"],roles:["Back of House","Management"],featured:false,lastUpdated:"2025-03-10",createdBy:"Alife Management"},
  {id:"s15",title:"Dress Code & Appearance Standards",category:"hr",subcategory:"Employee Standards",content:`# Dress Code & Appearance Standards\n\n## All Staff (Universal Requirements)\n- Clean, pressed uniform (concept-specific) \u2014 no stains, rips, or fading.\n- Closed-toe, non-slip shoes required at all times.\n- Name tag or branded identifier worn and visible.\n- Hair must be clean and pulled back (BOH: hair net or hat required).\n- Nails must be clean and short. No nail polish or acrylics for BOH staff.\n- Minimal fragrance \u2014 guests should smell the food, not you.\n\n## Front of House\n- Solid black pants (no jeans unless approved by GM).\n- Concept-branded shirt or approved all-black top.\n- Jewelry kept minimal and professional.\n- Tattoos: Visible tattoos are permitted unless offensive (manager discretion).\n\n## Back of House\n- Chef coat or concept-branded kitchen shirt.\n- Apron required during all prep and service.\n- Hair net or hat at all times \u2014 no exceptions.\n- No jewelry below the wrist \u2014 food safety requirement.\n\n## Bar Staff\n- Concept-branded top or approved black attire.\n- Watches permitted; no rings while handling garnishes or ice.\n\n## Non-Compliance\nFirst offense: Verbal warning and sent home to change (unpaid).\nSecond offense: Written warning.\nThird offense: Suspension pending review.`,tags:["dress code","appearance","uniform","grooming","HR"],locations:["All Locations"],roles:["All Staff"],featured:false,lastUpdated:"2025-01-20",createdBy:"Alife Management"},
  {id:"s16",title:"Social Media & Confidentiality Policy",category:"hr",subcategory:"Company Policies",content:`# Social Media & Confidentiality Policy\n\n## What You CAN Do\n- Share that you work at an Alife concept and express pride in the team.\n- Re-share official Alife social media posts.\n- Post personal photos at work (selfies, team shots) as long as no guests or confidential info are visible.\n\n## What You CANNOT Do\n- Post or share any proprietary recipes, batch formulas, or operational documents.\n- Photograph or video any kitchen operations, prep processes, or plating techniques.\n- Post content that includes identifiable guests without their written consent.\n- Comment publicly on guest complaints, incidents, or negative reviews.\n- Share internal financial information, sales numbers, or staffing details.\n- Post negative content about Alife, its concepts, coworkers, or management.\n- Use Alife branding, logos, or concept names in any personal business.\n\n## Handling Online Reviews\n- If you see a negative review, DO NOT respond. Forward it to your GM.\n- Only designated managers or ownership may respond to public reviews.\n\n## Confidential Information\nThe following are considered confidential:\n- Recipes, seasoning formulas, and proprietary techniques\n- Vendor names, pricing, and supply chain details\n- Financial data, revenue, labor costs, and profitability\n- Employee and guest personal information\n\n## Consequences\nViolation may result in immediate termination and potential legal action.`,tags:["social media","confidentiality","policy","reviews","proprietary","HR"],locations:["All Locations"],roles:["All Staff"],featured:false,lastUpdated:"2025-02-01",createdBy:"Alife Management"},
  {id:"s17",title:"Opening Checklist \u2014 Front of House",category:"operations",subcategory:"Daily Checklists",content:`# Opening Checklist \u2014 Front of House\n\n## 2 Hours Before Open\n- [ ] Unlock doors and disarm alarm\n- [ ] Turn on all lights and music (background level)\n- [ ] Check reservation list; pre-set any large parties\n- [ ] Stock host stand: menus, allergen binders, to-go supplies\n- [ ] Wipe down and sanitize all tables and chairs\n- [ ] Restock condiment caddies and napkin holders\n- [ ] Polish glassware and silverware\n\n## 1 Hour Before Open\n- [ ] Staff pre-shift meeting \u2014 review specials, 86\u2019d items, VIP guests\n- [ ] Check bathroom cleanliness and restock supplies\n- [ ] Confirm POS (Toast) is functioning \u2014 run a test void transaction\n- [ ] Verify all servers have server books and pens\n- [ ] Confirm bar is fully stocked and bar mats are clean\n- [ ] Walk the floor for anything out of place\n\n## 15 Minutes Before Open\n- [ ] Final manager walkthrough \u2014 manager signs off on floor\n- [ ] Confirm kitchen is ready and Expo is in position\n- [ ] Confirm sound levels are correct\n- [ ] Unlock front door\n- [ ] Host is at stand and ready to greet\n\n## Notes\nManager on duty must initial this checklist daily. Completed checklists stored at the host stand for 30 days.`,tags:["opening","checklist","FOH","daily"],locations:["All Locations"],roles:["Front of House","Management"],featured:false,lastUpdated:"2025-02-15",createdBy:"Alife Management"},
  {id:"s18",title:"Closing Checklist \u2014 Front of House",category:"operations",subcategory:"Daily Checklists",content:`# Closing Checklist \u2014 Front of House\n\n## Last Seating\n- [ ] No new tables seated after posted last-seating time\n- [ ] Inform remaining tables of last call for food and beverages\n- [ ] Begin pre-bussing vacated tables\n\n## Post-Service\n- [ ] All tables cleared, wiped, and sanitized\n- [ ] Chairs pushed in or stacked per location protocol\n- [ ] All condiments restocked for next day\n- [ ] Salt, pepper, and sugar caddies wiped and refilled\n- [ ] Floor swept and mopped (every section, under tables)\n- [ ] Bathrooms checked, cleaned, and restocked\n- [ ] Host stand organized: menus stacked, allergen binder put away\n\n## Bar Close\n- [ ] All bottles wiped, speed rails organized\n- [ ] Bar mats pulled and cleaned\n- [ ] Ice bin emptied and wiped\n- [ ] Garnishes wrapped and dated\n- [ ] Draft lines flushed per weekly schedule\n- [ ] Bar top wiped and sanitized\n\n## Manager Close\n- [ ] All staff checked out through Toast\n- [ ] Daily Sales Summary printed and reviewed\n- [ ] Cash drawer counted and reconciled\n- [ ] Manager Shift Log completed\n- [ ] All lights off, music off, alarm set\n- [ ] Doors locked \u2014 walk the building once before leaving\n\n## Notes\nNothing leaves the building without a manager sign-off. This includes food, alcohol, and supplies.`,tags:["closing","checklist","FOH","nightly","close"],locations:["All Locations"],roles:["Front of House","Bar","Management"],featured:false,lastUpdated:"2025-02-15",createdBy:"Alife Management"},
  {id:"s19",title:"Manager on Duty (MOD) Responsibilities",category:"operations",subcategory:"Management",content:`# Manager on Duty (MOD) Responsibilities\n\n## Before Service\n1. Arrive 30 minutes before staff to walk the building.\n2. Review reservations and anticipated covers.\n3. Check voicemail and email for overnight messages.\n4. Verify staffing: confirm all scheduled staff are present. Arrange covers for call-outs.\n5. Lead pre-shift meeting: specials, 86\u2019d items, VIP notes, and one coaching point.\n6. Sign off on Opening Checklist.\n\n## During Service\n- **Floor presence is non-negotiable.** You should be on the floor 80% of service, not in the office.\n- Touch every table at least once \u2014 introduce yourself and check in.\n- Monitor ticket times. If any ticket exceeds 15 minutes (lunch) or 20 minutes (dinner), intervene.\n- Handle all guest complaints personally (see Guest Complaint Resolution SOP).\n- Monitor staff performance: redirect, coach, or pull aside in real-time.\n- Authorize all voids, comps, and discounts in Toast.\n- Monitor bar and enforce TABC compliance.\n\n## After Service\n1. Complete all server and bartender checkouts.\n2. Reconcile cash drawer (see Cash Handling SOP).\n3. Complete the Manager Shift Log \u2014 required every shift, no exceptions.\n4. Walk the building: kitchen clean, bathrooms clean, floor clean, all equipment off.\n5. Set alarm, lock doors.\n\n## Manager Shift Log (Required Fields)\n- Date, shift, and your name\n- Total covers and sales for the shift\n- Staffing notes (call-outs, late arrivals, early cuts)\n- Guest complaint summary (if any)\n- 86\u2019d items and reasons\n- Maintenance or equipment issues\n- One positive callout (who did great work today)\n\n## Key Principle\nYou set the tone. If you\u2019re calm, the team is calm. If you\u2019re urgent, the team is urgent. Lead by example.`,tags:["MOD","manager","shift","leadership","operations","management"],locations:["All Locations"],roles:["Management"],featured:false,lastUpdated:"2025-02-25",createdBy:"Alife Management"},
  {id:"s20",title:"Equipment Failure & Maintenance Protocol",category:"operations",subcategory:"Facility Management",content:`# Equipment Failure & Maintenance Protocol\n\n## Immediate Steps for Any Equipment Failure\n1. Stop using the equipment immediately.\n2. If there is a safety hazard (fire, gas leak, electrical sparking), evacuate the area and call 911.\n3. Notify the Manager on Duty.\n4. Place a clear \u201COUT OF ORDER\u201D sign on the equipment.\n5. Document the issue: equipment name, time of failure, symptoms, and your name.\n\n## Common Equipment Issues\n\n### Walk-In Cooler / Freezer\n- If the temp rises above 41\u00b0F (cooler) or 0\u00b0F (freezer), begin relocating product immediately.\n- Call the refrigeration vendor within 30 minutes.\n- Log all product temperatures for insurance/health department purposes.\n\n### Flat Top / Grill\n- If the surface is not heating evenly, check the gas connection and pilot light.\n- Do NOT attempt repairs yourself. Call the equipment vendor.\n- Adjust the menu if necessary \u2014 notify FOH of any 86\u2019d items.\n\n### POS System (Toast)\n- Restart the terminal. If it doesn\u2019t resolve, call Toast support.\n- Revert to handwritten tickets as a backup.\n- All handwritten tickets must be entered into Toast once the system is back online.\n\n### Ice Machine\n- If not producing ice, check the water line and filter first.\n- If ice appears cloudy or has an odor, dump the bin and call the vendor.\n- Send a runner to get bagged ice in the meantime.\n\n## Preventive Maintenance\n- Walk-in temps logged twice daily (AM and PM) on the Temperature Log.\n- Equipment cleaning schedule posted in BOH \u2014 every station, every night.\n- Deep clean of all equipment monthly.\n- Report any unusual sounds, smells, or performance changes immediately.\n\n## Vendor Contacts\nPosted in the manager\u2019s binder at each location.`,tags:["equipment","maintenance","breakdown","cooler","POS","operations"],locations:["All Locations"],roles:["Back of House","Management"],featured:false,lastUpdated:"2025-02-08",createdBy:"Alife Management"},
  {id:"s21",title:"Toast POS \u2014 Quick Reference Guide",category:"quickref",subcategory:"Technology",content:`# Toast POS \u2014 Quick Reference Guide\n\n## Clocking In/Out\n1. Tap the clock icon on the Toast terminal.\n2. Enter your 4-digit PIN.\n3. Select \u201CClock In\u201D or \u201CClock Out.\u201D\n\n## Opening a New Table\n1. Tap \u201CNew Order\u201D on the main screen.\n2. Select the table number or \u201CTo-Go\u201D / \u201CBar.\u201D\n3. Enter the number of guests.\n4. Begin adding items.\n\n## Sending an Order\n1. After entering all items, tap \u201CSend.\u201D\n2. Review the order on the confirmation screen.\n3. Tap \u201CConfirm Send.\u201D The ticket prints in the kitchen.\n\n## Applying a Discount or Comp\n1. Open the check \u2192 tap the item \u2192 \u201CDiscount.\u201D\n2. Select the reason (Manager Comp, Service Recovery, Employee Discount).\n3. Manager must approve with their PIN.\n\n## Processing a Void\n1. Open the check \u2192 tap the item \u2192 \u201CVoid.\u201D\n2. Select the void reason.\n3. Manager approval required.\n\n## Splitting a Check\n1. Open the check \u2192 tap \u201CSplit.\u201D\n2. Choose: Split evenly, by item, or by seat.\n3. Process payment on each split check separately.\n\n## Closing a Check\n1. Tap \u201CPay\u201D on the check.\n2. Select payment type: Cash, Credit, Gift Card.\n3. For credit: swipe, insert, or tap the card.\n4. Print or email the receipt.\n\n## Troubleshooting\n- **Screen frozen:** Hold power button 10 seconds to restart.\n- **Printer not printing:** Check paper roll and connections. Power cycle.\n- **Card reader not working:** Try a different terminal.\n- **Toast support:** Phone number posted at the manager\u2019s station.`,tags:["Toast","POS","quick reference","technology","register","payment"],locations:["All Locations"],roles:["All Staff"],featured:false,lastUpdated:"2025-01-30",createdBy:"Alife Management"},
  {id:"s22",title:"Knowledge Portal \u2014 User Guide",category:"quickref",subcategory:"Technology",content:`# Knowledge Portal \u2014 User Guide\n\n## What Is This Portal?\nThe Alife Knowledge Portal is the company\u2019s centralized, searchable database for every SOP, training document, recipe, checklist, and policy you need to do your job. It\u2019s available 24/7 from any device.\n\n## How to Find a Document\n**Search:** Type any keyword in the search bar \u2014 titles, topics, ingredients, or tags all work.\n**Browse:** Click a category tile on the home screen (SOPs, Training, Recipes, HR, Operations, Quick Reference).\n**Filter:** Use the Location and Role dropdowns to narrow results to your concept and department.\n\n## Document Features\n- **Featured Docs (gold star):** Critical documents all staff must read.\n- **Breadcrumb Navigation:** Home > Category > Document \u2014 click any level to go back.\n- **Categories & Subcategories:** Documents are organized into 6 categories, each with subcategories.\n- **Tags:** Keywords that help search find the right document.\n\n## For Management \u2014 Admin Mode\n1. Click \u201CAdmin Login\u201D (top-right) and enter the admin password.\n2. You can now Add, Edit, and Delete documents.\n3. Use \u201CFeatured\u201D toggle for must-read docs.\n4. Use Markdown formatting in the content editor (# for headings, ** for bold, - for bullets).\n5. Always tag documents with location, role, and 3\u20135 keyword tags.\n6. Click \u201CExit Admin\u201D when done.\n\n## Staff Expectations\n- Bookmark this portal on your phone.\n- Search before you ask.\n- Review all Featured documents in your first week.\n- Report errors or outdated info to your manager.`,tags:["portal","guide","how to","help","user guide","knowledge base"],locations:["All Locations"],roles:["All Staff"],featured:true,lastUpdated:"2026-03-27",createdBy:"Alife Management"}
];

function renderContent(text) {
  if (!text) return "";
  const lines = text.split("\n");
  let html = "", inUl = false, inOl = false;
  const closeList = () => { if (inUl) { html += "</ul>"; inUl = false; } if (inOl) { html += "</ol>"; inOl = false; } };
  const inline = (s) => s.replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>").replace(/\*(.*?)\*/g, "<em>$1</em>").replace(/`(.*?)`/g, "<code>$1</code>");
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.startsWith("# ")) { closeList(); html += `<h1 class="md-h1">${inline(line.slice(2))}</h1>`; }
    else if (line.startsWith("## ")) { closeList(); html += `<h2 class="md-h2">${inline(line.slice(3))}</h2>`; }
    else if (line.startsWith("### ")) { closeList(); html += `<h3 class="md-h3">${inline(line.slice(4))}</h3>`; }
    else if (line.match(/^- \[[ x]\] /)) { if (!inUl) { html += `<ul class="checklist">`; inUl = true; } const checked = line[3] !== " "; html += `<li class="check-item ${checked?"checked":""}"><span class="checkbox ${checked?"checked":""}">${checked?"✓":""}</span> ${inline(line.slice(6))}</li>`; }
    else if (line.startsWith("- ")) { if (inOl) { html += "</ol>"; inOl = false; } if (!inUl) { html += "<ul>"; inUl = true; } html += `<li>${inline(line.slice(2))}</li>`; }
    else if (line.match(/^\d+\. /)) { if (inUl) { html += "</ul>"; inUl = false; } if (!inOl) { html += "<ol>"; inOl = true; } html += `<li>${inline(line.replace(/^\d+\. /, ""))}</li>`; }
    else if (line === "") { closeList(); html += `<div class="md-spacer"></div>`; }
    else { closeList(); html += `<p>${inline(line)}</p>`; }
  }
  closeList();
  return html;
}

function timeAgo(dateStr) { const d = new Date(dateStr); const diff = Math.floor((Date.now() - d) / 86400000); if (diff === 0) return "Today"; if (diff === 1) return "Yesterday"; if (diff < 30) return `${diff} days ago`; if (diff < 365) return `${Math.floor(diff / 30)}mo ago`; return `${Math.floor(diff / 365)}yr ago`; }
function getCatMeta(id) { return CATEGORIES.find(c => c.id === id) || CATEGORIES[0]; }
function uid() { return "doc-" + Math.random().toString(36).slice(2, 11) + "-" + Date.now(); }

export default function AlifePortal() {
  useEffect(() => { const el = document.createElement("link"); el.href = "https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Barlow:ital,wght@0,300;0,400;0,500;0,600;0,700;1,400&display=swap"; el.rel = "stylesheet"; document.head.appendChild(el); }, []);

  const [docs, setDocs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [view, setView] = useState("home");
  const [selCat, setSelCat] = useState(null);
  const [selDoc, setSelDoc] = useState(null);
  const [query, setQuery] = useState("");
  const [locFilter, setLocFilter] = useState("All Locations");
  const [roleFilter, setRoleFilter] = useState("All Staff");
  const [isAdmin, setIsAdmin] = useState(false);
  const [pwInput, setPwInput] = useState("");
  const [pwError, setPwError] = useState(false);
  const [showLogin, setShowLogin] = useState(false);
  const [editDoc, setEditDoc] = useState(null);
  const [deleteConfirm, setDeleteConfirm] = useState(null);
  const [saveMsg, setSaveMsg] = useState("");
  const [uploading, setUploading] = useState(false);
  const searchRef = useRef(null);
  const fileInputRef = useRef(null);
  const emptyForm = { title:"", category:"sops", subcategory:"", content:"", tags:"", locations:["All Locations"], roles:["All Staff"], featured:false, fileName:"", fileURL:"", fileType:"" };
  const [form, setForm] = useState(emptyForm);
  const [pendingFile, setPendingFile] = useState(null);
  const [recipesUnlocked, setRecipesUnlocked] = useState(false);
  const [showRecipeLock, setShowRecipeLock] = useState(false);
  const [recipePwInput, setRecipePwInput] = useState("");
  const [recipePwError, setRecipePwError] = useState(false);
  const [recipeLockTarget, setRecipeLockTarget] = useState(null); // "category" or a doc object

  useEffect(() => {
    const colRef = collection(db, "documents");
    // Real-time listener: any admin change updates ALL connected browsers instantly
    const unsubscribe = onSnapshot(colRef, (snapshot) => {
      if (snapshot.empty) {
        // First time: seed the database with all 22 docs
        const seedDB = async () => {
          const batch = writeBatch(db);
          SEED_DOCS.forEach(d => {
            batch.set(doc(db, "documents", d.id), d);
          });
          await batch.commit();
        };
        seedDB();
      } else {
        const loaded = snapshot.docs.map(d => d.data());
        setDocs(loaded);
      }
      setLoading(false);
    }, (error) => {
      console.error("Firebase error:", error);
      // Fallback to seed docs if Firebase fails
      setDocs(SEED_DOCS);
      setLoading(false);
    });
    return () => unsubscribe();
  }, []);

  const saveDocs = useCallback(async (updated) => { setDocs(updated); }, []);

  const searchResults = useCallback(() => {
    if (!query.trim()) return [];
    const q = query.toLowerCase();
    return docs.filter(d => {
      if (d.category === "recipes" && !recipesUnlocked && !isAdmin) return false;
      const loc = locFilter === "All Locations" || (d.locations || []).includes("All Locations") || (d.locations || []).includes(locFilter);
      const role = roleFilter === "All Staff" || (d.roles || []).includes("All Staff") || (d.roles || []).includes(roleFilter);
      const match = d.title.toLowerCase().includes(q) || (d.content || "").toLowerCase().includes(q) || (d.tags || []).some(t => t.toLowerCase().includes(q)) || (d.subcategory || "").toLowerCase().includes(q);
      return loc && role && match;
    });
  }, [docs, query, locFilter, roleFilter, recipesUnlocked, isAdmin]);

  const filteredByCat = useCallback((catId) => {
    return docs.filter(d => {
      const loc = locFilter === "All Locations" || (d.locations || []).includes("All Locations") || (d.locations || []).includes(locFilter);
      const role = roleFilter === "All Staff" || (d.roles || []).includes("All Staff") || (d.roles || []).includes(roleFilter);
      return d.category === catId && loc && role;
    });
  }, [docs, locFilter, roleFilter]);

  const handleLogin = () => { if (pwInput === ADMIN_PASSWORD) { setIsAdmin(true); setShowLogin(false); setPwInput(""); setPwError(false); } else { setPwError(true); } };
  const openNew = () => { setForm(emptyForm); setEditDoc(null); setPendingFile(null); setView("edit"); };
  const openEdit = (doc) => { setForm({ title: doc.title, category: doc.category, subcategory: doc.subcategory || "", content: doc.content || "", tags: (doc.tags || []).join(", "), locations: doc.locations || ["All Locations"], roles: doc.roles || ["All Staff"], featured: doc.featured || false, fileName: doc.fileName || "", fileURL: doc.fileURL || "", fileType: doc.fileType || "" }); setEditDoc(doc); setPendingFile(null); setView("edit"); };

  const handleSave = async () => {
    if (!form.title.trim() || (!form.content.trim() && !pendingFile && !form.fileURL)) return;
    setUploading(true);
    const now = new Date().toISOString().slice(0, 10);
    let fileName = form.fileName || "";
    let fileURL = form.fileURL || "";
    let fileType = form.fileType || "";

    // Upload new file if one is pending
    if (pendingFile) {
      try {
        const docId = editDoc ? editDoc.id : uid();
        const ext = pendingFile.name.split('.').pop().toLowerCase();
        const storageRef = ref(storage, `documents/${docId}/${pendingFile.name}`);
        await uploadBytes(storageRef, pendingFile);
        fileURL = await getDownloadURL(storageRef);
        fileName = pendingFile.name;
        fileType = ext;

        // If editing and replacing an old file, delete the old one
        if (editDoc && editDoc.fileURL && editDoc.fileName) {
          try {
            const oldRef = ref(storage, `documents/${editDoc.id}/${editDoc.fileName}`);
            await deleteObject(oldRef);
          } catch(e) { /* old file may not exist */ }
        }

        const newDoc = { id: editDoc ? editDoc.id : docId, title: form.title.trim(), category: form.category, subcategory: form.subcategory, content: form.content, tags: form.tags.split(",").map(t => t.trim()).filter(Boolean), locations: form.locations.length ? form.locations : ["All Locations"], roles: form.roles.length ? form.roles : ["All Staff"], featured: form.featured, lastUpdated: now, createdBy: "Admin", fileName, fileURL, fileType };
        await setDoc(doc(db, "documents", newDoc.id), newDoc);
      } catch(e) { console.error("Upload error:", e); }
    } else {
      const newDoc = { id: editDoc ? editDoc.id : uid(), title: form.title.trim(), category: form.category, subcategory: form.subcategory, content: form.content, tags: form.tags.split(",").map(t => t.trim()).filter(Boolean), locations: form.locations.length ? form.locations : ["All Locations"], roles: form.roles.length ? form.roles : ["All Staff"], featured: form.featured, lastUpdated: now, createdBy: "Admin", fileName, fileURL, fileType };
      try { await setDoc(doc(db, "documents", newDoc.id), newDoc); } catch(e) { console.error("Save error:", e); }
    }

    setUploading(false);
    setPendingFile(null);
    setSaveMsg("Saved!"); setTimeout(() => setSaveMsg(""), 2000);
    setView("admin");
  };

  const handleDelete = async (id) => {
    // Also delete file from storage if one exists
    const docToDelete = docs.find(d => d.id === id);
    if (docToDelete && docToDelete.fileURL && docToDelete.fileName) {
      try { await deleteObject(ref(storage, `documents/${id}/${docToDelete.fileName}`)); } catch(e) { /* file may not exist */ }
    }
    try { await deleteDoc(doc(db, "documents", id)); } catch(e) { console.error("Delete error:", e); }
    setDeleteConfirm(null);
    if (selDoc?.id === id) { setSelDoc(null); setView("home"); }
  };
  const toggleLocForm = (loc) => setForm(f => ({ ...f, locations: f.locations.includes(loc) ? f.locations.filter(l => l !== loc) : [...f.locations, loc] }));
  const toggleRoleForm = (role) => setForm(f => ({ ...f, roles: f.roles.includes(role) ? f.roles.filter(r => r !== role) : [...f.roles, role] }));
  const goHome = () => { setView("home"); setSelCat(null); setSelDoc(null); setQuery(""); };
  const goCategory = (cat) => {
    if (cat === "recipes" && !recipesUnlocked && !isAdmin) { setRecipeLockTarget("category"); setShowRecipeLock(true); return; }
    setSelCat(cat); setView("category"); setSelDoc(null);
  };
  const goDoc = (docObj) => {
    if (docObj.category === "recipes" && !recipesUnlocked && !isAdmin) { setRecipeLockTarget(docObj); setShowRecipeLock(true); return; }
    setSelDoc(docObj); setView("doc");
  };
  const goSearch = (q) => { setQuery(q); setView("search"); };

  const handleRecipeUnlock = () => {
    if (recipePwInput === RECIPE_PASSWORD) {
      setRecipesUnlocked(true); setShowRecipeLock(false); setRecipePwInput(""); setRecipePwError(false);
      if (recipeLockTarget === "category") { setSelCat("recipes"); setView("category"); setSelDoc(null); }
      else if (recipeLockTarget && typeof recipeLockTarget === "object") { setSelDoc(recipeLockTarget); setView("doc"); }
      setRecipeLockTarget(null);
    } else { setRecipePwError(true); }
  };

  const s = {
    wrap: { fontFamily:"'Barlow', sans-serif", background:"#0F0F0F", minHeight:"100vh", color:"#F7F5F0", display:"flex", flexDirection:"column" },
    header: { background:"#1A1A1A", borderBottom:"1px solid #2A2A2A", padding:"0 24px", display:"flex", alignItems:"center", gap:16, height:64, flexShrink:0, flexWrap:"wrap" },
    logo: { fontFamily:"'Bebas Neue', sans-serif", fontSize:28, letterSpacing:3, color:"#C8952A", cursor:"pointer", userSelect:"none" },
    logoSub: { fontSize:10, color:"#666", letterSpacing:2, textTransform:"uppercase", marginTop:-4 },
    searchBar: { flex:1, maxWidth:480, minWidth:180, display:"flex", alignItems:"center", background:"#252525", border:"1px solid #333", borderRadius:8, padding:"0 14px", gap:10, height:40 },
    searchInput: { flex:1, background:"none", border:"none", outline:"none", color:"#F7F5F0", fontSize:14, fontFamily:"'Barlow', sans-serif" },
    filterBar: { background:"#141414", borderBottom:"1px solid #222", padding:"10px 24px", display:"flex", gap:12, alignItems:"center", flexWrap:"wrap" },
    filterLabel: { fontSize:11, color:"#666", textTransform:"uppercase", letterSpacing:1 },
    select: { background:"#1E1E1E", border:"1px solid #333", borderRadius:6, color:"#F7F5F0", padding:"5px 10px", fontSize:13, fontFamily:"'Barlow', sans-serif", outline:"none", cursor:"pointer" },
    main: { flex:1, padding:"28px 24px", maxWidth:1100, width:"100%", margin:"0 auto", boxSizing:"border-box" },
    sectionTitle: { fontFamily:"'Bebas Neue', sans-serif", fontSize:22, letterSpacing:2, color:"#C8952A", marginBottom:16 },
    catGrid: { display:"grid", gridTemplateColumns:"repeat(auto-fill, minmax(200px, 1fr))", gap:16, marginBottom:36 },
    catCard: () => ({ background:"#1A1A1A", border:"1px solid #2A2A2A", borderRadius:12, padding:"20px 18px", cursor:"pointer", transition:"all 0.2s", display:"flex", flexDirection:"column", gap:8 }),
    docList: { display:"flex", flexDirection:"column", gap:8 },
    docCard: { background:"#1A1A1A", border:"1px solid #2A2A2A", borderRadius:10, padding:"14px 18px", cursor:"pointer", transition:"all 0.15s", display:"flex", justifyContent:"space-between", alignItems:"flex-start", gap:12 },
    docTitle: { fontSize:15, fontWeight:600, color:"#F7F5F0", marginBottom:4, lineHeight:1.4 },
    docMeta: { display:"flex", gap:10, flexWrap:"wrap", alignItems:"center" },
    pill: (color) => ({ display:"inline-flex", alignItems:"center", gap:4, background:`${color}22`, color, padding:"2px 10px", borderRadius:20, fontSize:11, fontWeight:600, letterSpacing:0.5 }),
    tag: { background:"#252525", color:"#888", padding:"2px 8px", borderRadius:4, fontSize:11 },
    btn: (v) => ({ display:"inline-flex", alignItems:"center", gap:6, padding:"8px 18px", borderRadius:8, fontSize:13, fontWeight:600, cursor:"pointer", fontFamily:"'Barlow', sans-serif", letterSpacing:0.5, transition:"all 0.15s", background: v==="gold"?"#C8952A":v==="danger"?"#B03A2E":v==="ghost"?"transparent":"#252525", color: v==="ghost"?"#888":"#F7F5F0", border: v==="ghost"?"1px solid #333":"none" }),
    docView: { maxWidth:740, margin:"0 auto" },
    docHeader: { marginBottom:28, paddingBottom:20, borderBottom:"1px solid #2A2A2A" },
    breadcrumb: { display:"flex", alignItems:"center", gap:8, fontSize:12, color:"#666", marginBottom:16, flexWrap:"wrap" },
    docContent: { lineHeight:1.8, fontSize:15 },
    adminGrid: { display:"grid", gridTemplateColumns:"repeat(auto-fill, minmax(340px, 1fr))", gap:12 },
    adminCard: { background:"#1A1A1A", border:"1px solid #2A2A2A", borderRadius:10, padding:"14px 16px" },
    formGroup: { marginBottom:18 },
    label: { display:"block", fontSize:12, color:"#C8952A", fontWeight:600, letterSpacing:1, textTransform:"uppercase", marginBottom:6 },
    input: { width:"100%", background:"#1E1E1E", border:"1px solid #333", borderRadius:8, padding:"10px 14px", color:"#F7F5F0", fontSize:14, fontFamily:"'Barlow', sans-serif", outline:"none", boxSizing:"border-box" },
    textarea: { width:"100%", background:"#1E1E1E", border:"1px solid #333", borderRadius:8, padding:"12px 14px", color:"#F7F5F0", fontSize:13, fontFamily:"'Barlow', sans-serif", outline:"none", boxSizing:"border-box", resize:"vertical", lineHeight:1.6, minHeight:320 },
    toast: { position:"fixed", bottom:24, right:24, background:"#5CB85C", color:"#fff", padding:"10px 20px", borderRadius:8, fontWeight:600, fontSize:14, zIndex:1000 },
    modal: { position:"fixed", inset:0, background:"rgba(0,0,0,0.75)", display:"flex", alignItems:"center", justifyContent:"center", zIndex:999 },
    modalBox: { background:"#1A1A1A", border:"1px solid #333", borderRadius:14, padding:28, width:340, maxWidth:"90vw" },
    multiChip: (a) => ({ padding:"5px 12px", borderRadius:20, fontSize:12, fontWeight:600, cursor:"pointer", border:"none", background: a?"#C8952A":"#252525", color: a?"#0F0F0F":"#888", fontFamily:"'Barlow', sans-serif", transition:"all 0.15s" }),
  };

  const docCSS = `.md-h1{font-family:'Bebas Neue',sans-serif;font-size:26px;letter-spacing:2px;color:#C8952A;margin:0 0 4px;}.md-h2{font-size:16px;font-weight:700;color:#E8B84B;margin:20px 0 8px;padding-bottom:6px;border-bottom:1px solid #2A2A2A;}.md-h3{font-size:14px;font-weight:700;color:#F7F5F0;margin:14px 0 6px;}p{margin:4px 0 8px;color:#D4D0CA;}ul,ol{margin:6px 0 12px 20px;color:#D4D0CA;}li{margin-bottom:4px;}strong{color:#F7F5F0;font-weight:700;}em{color:#C8952A;font-style:italic;}code{background:#252525;padding:2px 7px;border-radius:4px;font-size:12px;color:#C8952A;}.checklist{list-style:none;margin-left:0;padding:0;}.check-item{display:flex;align-items:flex-start;gap:10px;padding:5px 0;color:#D4D0CA;}.checkbox{width:18px;height:18px;border:2px solid #444;border-radius:4px;display:inline-flex;align-items:center;justify-content:center;flex-shrink:0;margin-top:2px;font-size:10px;}.checkbox.checked{background:#5CB85C;border-color:#5CB85C;color:#fff;}.md-spacer{height:6px;}.doc-card-hover:hover{background:#222!important;border-color:#C8952A44!important;}.cat-card-hover:hover{border-color:#C8952A!important;background:#1E1E1E!important;}.btn-hover:hover{opacity:0.85;}input[type=text],input[type=password],select,textarea{transition:border-color 0.15s;}input[type=text]:focus,input[type=password]:focus,select:focus,textarea:focus{border-color:#C8952A!important;}`;

  if (loading) return (<div style={{...s.wrap, alignItems:"center", justifyContent:"center", gap:16}}><style>{docCSS}</style><div style={{fontFamily:"'Bebas Neue',sans-serif", fontSize:36, letterSpacing:4, color:"#C8952A"}}>ALIFE</div><div style={{color:"#666", fontSize:14}}>Loading portal...</div></div>);

  const DocCard = ({ doc, showActions }) => { const cat = getCatMeta(doc.category); const Icon = cat.icon; return (
    <div className="doc-card-hover" style={s.docCard} onClick={() => goDoc(doc)}>
      <div style={{flex:1, minWidth:0}}>
        <div style={{display:"flex", alignItems:"flex-start", gap:8, marginBottom:6}}>
          {doc.featured && <Star size={13} style={{color:"#C8952A", flexShrink:0, marginTop:3}} />}
          <div style={s.docTitle}>{doc.title}</div>
        </div>
        <div style={s.docMeta}>
          <span style={s.pill(cat.color)}><Icon size={10}/> {cat.label}</span>
          {doc.subcategory && <span style={s.tag}>{doc.subcategory}</span>}
          {doc.fileURL && <span style={{...s.tag, color:"#5CB85C", background:"#5CB85C22"}}>📎 {doc.fileType?.toUpperCase()}</span>}
          {(doc.locations||[]).includes("All Locations") ? null : (doc.locations||[]).slice(0,2).map(l => <span key={l} style={{...s.tag, color:"#C8952A"}}>{l}</span>)}
          <span style={{...s.tag, marginLeft:"auto"}}><Clock size={10} style={{display:"inline",marginRight:3}}/>{timeAgo(doc.lastUpdated)}</span>
        </div>
      </div>
      {showActions && isAdmin && (<div style={{display:"flex", gap:6, flexShrink:0}} onClick={e => e.stopPropagation()}><button className="btn-hover" style={s.btn("ghost")} onClick={() => openEdit(doc)}><Edit3 size={13}/></button><button className="btn-hover" style={s.btn("danger")} onClick={() => setDeleteConfirm(doc)}><Trash2 size={13}/></button></div>)}
      {!showActions && <ChevronRight size={16} style={{color:"#444", flexShrink:0, marginTop:3}}/>}
    </div>
  ); };

  const Header = () => (<header style={s.header}><div style={{display:"flex", flexDirection:"column", cursor:"pointer"}} onClick={goHome}><div style={s.logo}>ALIFE</div><div style={s.logoSub}>Knowledge Portal</div></div><div style={s.searchBar}><Search size={15} color="#666"/><input ref={searchRef} style={s.searchInput} placeholder="Search documents, SOPs, recipes..." value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => { if (e.key === "Enter" && query.trim()) goSearch(query); }}/>{query && <X size={14} color="#666" style={{cursor:"pointer"}} onClick={() => { setQuery(""); if(view==="search") goHome(); }} />}</div>{query.trim() && <button className="btn-hover" style={s.btn("gold")} onClick={() => goSearch(query)}>Search</button>}<div style={{marginLeft:"auto", display:"flex", gap:8, alignItems:"center"}}>{isAdmin && <button className="btn-hover" style={s.btn("gold")} onClick={() => setView("admin")}><Settings size={13}/> Admin</button>}<button className="btn-hover" style={s.btn("ghost")} onClick={() => isAdmin ? setIsAdmin(false) : setShowLogin(true)}>{isAdmin ? <><LogOut size={13}/> Exit Admin</> : <><Lock size={13}/> Admin</>}</button></div></header>);

  const FilterBar = () => (<div style={s.filterBar}><span style={s.filterLabel}>Filter by</span><select style={s.select} value={locFilter} onChange={e => setLocFilter(e.target.value)}>{LOCATIONS.map(l => <option key={l}>{l}</option>)}</select><select style={s.select} value={roleFilter} onChange={e => setRoleFilter(e.target.value)}>{ROLES.map(r => <option key={r}>{r}</option>)}</select>{(locFilter !== "All Locations" || roleFilter !== "All Staff") && <button className="btn-hover" style={s.btn("ghost")} onClick={() => { setLocFilter("All Locations"); setRoleFilter("All Staff"); }}><X size={12}/> Clear</button>}<span style={{marginLeft:"auto", fontSize:12, color:"#555"}}>{docs.length} documents loaded</span></div>);

  const HomeView = () => { const hideRecipes = !recipesUnlocked && !isAdmin; const featured = docs.filter(d => d.featured && !(hideRecipes && d.category === "recipes")).slice(0, 8); const recent = [...docs].filter(d => !(hideRecipes && d.category === "recipes")).sort((a,b) => b.lastUpdated.localeCompare(a.lastUpdated)).slice(0, 5); return (
    <div>
      <div style={{marginBottom:32}}><div style={{fontFamily:"'Bebas Neue',sans-serif", fontSize:38, letterSpacing:3, marginBottom:6}}><span style={{color:"#C8952A"}}>ALIFE</span> KNOWLEDGE BASE</div><div style={{color:"#888", fontSize:15}}>{docs.length} documents across {CATEGORIES.length} categories \u2014 search or browse below.</div></div>
      <div style={s.sectionTitle}>Browse by Category</div>
      <div style={s.catGrid}>{CATEGORIES.map(cat => { const Icon = cat.icon; const count = filteredByCat(cat.id).length; const locked = cat.id === "recipes" && !recipesUnlocked && !isAdmin; return (<div key={cat.id} className="cat-card-hover" style={s.catCard()} onClick={() => goCategory(cat.id)}><div style={{display:"flex", alignItems:"center", justifyContent:"space-between"}}><Icon size={22} color={cat.color}/>{locked && <Lock size={14} color="#666"/>}</div><div style={{fontFamily:"'Bebas Neue',sans-serif", fontSize:18, letterSpacing:1.5, color:"#F7F5F0"}}>{cat.label}{locked ? " 🔒" : ""}</div><div style={{fontSize:12, color:"#666"}}>{cat.desc}</div><div style={{fontSize:12, color:cat.color, fontWeight:600, marginTop:4}}>{count} doc{count !== 1 ? "s" : ""}</div></div>); })}</div>
      {featured.length > 0 && (<><div style={{...s.sectionTitle, display:"flex", alignItems:"center", gap:8}}><Star size={16} color="#C8952A"/> Featured Documents</div><div style={{...s.docList, marginBottom:32}}>{featured.map(d => <DocCard key={d.id} doc={d}/>)}</div></>)}
      <div style={s.sectionTitle}>Recently Updated</div>
      <div style={s.docList}>{recent.map(d => <DocCard key={d.id} doc={d}/>)}</div>
    </div>
  ); };

  const CategoryView = () => { const cat = getCatMeta(selCat); const Icon = cat.icon; const catDocs = filteredByCat(selCat); const subcats = [...new Set(catDocs.map(d => d.subcategory).filter(Boolean))]; return (
    <div>
      <button className="btn-hover" style={{...s.btn("ghost"), marginBottom:20}} onClick={goHome}><ArrowLeft size={14}/> Back</button>
      <div style={{display:"flex", alignItems:"center", gap:14, marginBottom:24}}><Icon size={28} color={cat.color}/><div><div style={{fontFamily:"'Bebas Neue',sans-serif", fontSize:30, letterSpacing:2, color:cat.color}}>{cat.label}</div><div style={{fontSize:13, color:"#666"}}>{catDocs.length} document{catDocs.length !== 1 ? "s" : ""}</div></div>{isAdmin && <button className="btn-hover" style={{...s.btn("gold"), marginLeft:"auto"}} onClick={() => { setForm({...emptyForm, category:selCat}); setEditDoc(null); setView("edit"); }}><Plus size={14}/> Add Document</button>}</div>
      {catDocs.length === 0 && <div style={{color:"#666", fontSize:14, padding:"40px 0", textAlign:"center"}}>No documents found for your current filters.</div>}
      {subcats.length > 0 ? subcats.map(sub => (<div key={sub} style={{marginBottom:24}}><div style={{fontSize:12, color:"#C8952A", fontWeight:700, letterSpacing:2, textTransform:"uppercase", marginBottom:8, paddingBottom:6, borderBottom:"1px solid #222"}}>{sub}</div><div style={s.docList}>{catDocs.filter(d => d.subcategory === sub).map(d => <DocCard key={d.id} doc={d}/>)}</div></div>)) : <div style={s.docList}>{catDocs.map(d => <DocCard key={d.id} doc={d}/>)}</div>}
    </div>
  ); };

  const DocView = () => { if (!selDoc) return null; const cat = getCatMeta(selDoc.category); return (
    <div style={s.docView}>
      <div style={s.breadcrumb}><span style={{cursor:"pointer", color:"#C8952A"}} onClick={goHome}>Home</span><ChevronRight size={12}/><span style={{cursor:"pointer"}} onClick={() => goCategory(selDoc.category)}>{cat.label}</span><ChevronRight size={12}/><span style={{color:"#888"}}>{selDoc.title}</span></div>
      <div style={s.docHeader}>
        <div style={{display:"flex", justifyContent:"space-between", alignItems:"flex-start", gap:12, flexWrap:"wrap"}}>
          <div><div style={{fontFamily:"'Bebas Neue',sans-serif", fontSize:32, letterSpacing:2, color:"#F7F5F0", marginBottom:8}}>{selDoc.title}</div><div style={{display:"flex", gap:8, flexWrap:"wrap"}}><span style={s.pill(cat.color)}>{cat.label}</span>{selDoc.subcategory && <span style={s.tag}>{selDoc.subcategory}</span>}{(selDoc.locations||[]).includes("All Locations") ? <span style={s.pill("#666")}>All Locations</span> : (selDoc.locations||[]).map(l => <span key={l} style={s.pill("#C8952A")}>{l}</span>)}</div></div>
          {isAdmin && <div style={{display:"flex", gap:8}}><button className="btn-hover" style={s.btn("ghost")} onClick={() => openEdit(selDoc)}><Edit3 size={13}/> Edit</button><button className="btn-hover" style={s.btn("danger")} onClick={() => setDeleteConfirm(selDoc)}><Trash2 size={13}/></button></div>}
        </div>
        <div style={{marginTop:12, display:"flex", gap:16, fontSize:12, color:"#555", flexWrap:"wrap"}}><span><Clock size={11} style={{display:"inline",marginRight:4}}/>Updated {timeAgo(selDoc.lastUpdated)}</span>{(selDoc.tags||[]).length > 0 && <span><Tag size={11} style={{display:"inline",marginRight:4}}/>{(selDoc.tags||[]).join(", ")}</span>}</div>
      </div>
      <style>{docCSS}</style>
      {selDoc.content && <div style={s.docContent} dangerouslySetInnerHTML={{__html: renderContent(selDoc.content)}}/>}
      {selDoc.fileURL && (
        <div style={{marginTop: selDoc.content ? 28 : 0}}>
          {selDoc.fileType === "pdf" ? (
            <div>
              <div style={{fontSize:12, color:"#C8952A", fontWeight:700, letterSpacing:2, textTransform:"uppercase", marginBottom:12}}>Attached Document</div>
              <iframe src={selDoc.fileURL} style={{width:"100%", height:600, border:"1px solid #2A2A2A", borderRadius:8, background:"#fff"}} title={selDoc.fileName}/>
              <div style={{marginTop:8}}><a href={selDoc.fileURL} target="_blank" rel="noopener noreferrer" style={{color:"#C8952A", fontSize:13, fontWeight:600, textDecoration:"none"}}>Open PDF in new tab &rarr;</a></div>
            </div>
          ) : (selDoc.fileType === "png" || selDoc.fileType === "jpg" || selDoc.fileType === "jpeg" || selDoc.fileType === "gif") ? (
            <div>
              <div style={{fontSize:12, color:"#C8952A", fontWeight:700, letterSpacing:2, textTransform:"uppercase", marginBottom:12}}>Attached Image</div>
              <img src={selDoc.fileURL} alt={selDoc.fileName} style={{maxWidth:"100%", borderRadius:8, border:"1px solid #2A2A2A"}}/>
            </div>
          ) : (
            <div style={{background:"#1A1A1A", border:"1px solid #2A2A2A", borderRadius:10, padding:20, display:"flex", alignItems:"center", gap:14}}>
              <FileText size={28} color="#C8952A"/>
              <div style={{flex:1}}>
                <div style={{fontWeight:600, fontSize:14, marginBottom:4}}>{selDoc.fileName}</div>
                <div style={{fontSize:12, color:"#666"}}>{selDoc.fileType.toUpperCase()} file</div>
              </div>
              <a href={selDoc.fileURL} target="_blank" rel="noopener noreferrer" style={{textDecoration:"none"}}><button className="btn-hover" style={s.btn("gold")}>Download</button></a>
            </div>
          )}
        </div>
      )}
      <div style={{marginTop:40, paddingTop:20, borderTop:"1px solid #2A2A2A"}}><button className="btn-hover" style={s.btn("ghost")} onClick={() => view === "search" ? goSearch(query) : goCategory(selDoc.category)}><ArrowLeft size={14}/> Back</button></div>
    </div>
  ); };

  const SearchView = () => { const results = searchResults(); return (
    <div>
      <button className="btn-hover" style={{...s.btn("ghost"), marginBottom:20}} onClick={goHome}><ArrowLeft size={14}/> Back</button>
      <div style={{marginBottom:20}}><div style={{fontFamily:"'Bebas Neue',sans-serif", fontSize:24, letterSpacing:2, color:"#F7F5F0"}}>SEARCH: <span style={{color:"#C8952A"}}>"{query}"</span></div><div style={{fontSize:13, color:"#666"}}>{results.length} result{results.length !== 1 ? "s" : ""}</div></div>
      {results.length === 0 ? <div style={{color:"#666", padding:"40px 0", textAlign:"center"}}>No results found. Try different keywords.</div> : <div style={s.docList}>{results.map(d => <DocCard key={d.id} doc={d}/>)}</div>}
    </div>
  ); };

  const AdminView = () => (<div>
    <button className="btn-hover" style={{...s.btn("ghost"), marginBottom:20}} onClick={goHome}><ArrowLeft size={14}/> Back</button>
    <div style={{display:"flex", alignItems:"center", justifyContent:"space-between", marginBottom:24, flexWrap:"wrap", gap:12}}><div><div style={{fontFamily:"'Bebas Neue',sans-serif", fontSize:28, letterSpacing:2, color:"#C8952A"}}>ADMIN PANEL</div><div style={{fontSize:13, color:"#666"}}>{docs.length} total documents</div></div><button className="btn-hover" style={s.btn("gold")} onClick={openNew}><Plus size={14}/> New Document</button></div>
    <div style={s.adminGrid}>{docs.map(doc => { const cat = getCatMeta(doc.category); const Icon = cat.icon; return (<div key={doc.id} style={s.adminCard}><div style={{display:"flex", justifyContent:"space-between", alignItems:"flex-start", marginBottom:8}}><div style={{flex:1, minWidth:0, paddingRight:8}}><div style={{fontSize:14, fontWeight:600, marginBottom:4, lineHeight:1.4}}>{doc.title}</div><span style={s.pill(cat.color)}><Icon size={10}/> {cat.label}</span></div><div style={{display:"flex", gap:6, flexShrink:0}}><button className="btn-hover" style={s.btn("ghost")} onClick={() => openEdit(doc)}><Edit3 size={12}/></button><button className="btn-hover" style={s.btn("danger")} onClick={() => setDeleteConfirm(doc)}><Trash2 size={12}/></button></div></div><div style={{fontSize:11, color:"#555", marginTop:4}}>Updated {timeAgo(doc.lastUpdated)}</div></div>); })}</div>
  </div>);

  const EditView = () => (<div style={{maxWidth:740, margin:"0 auto"}}>
    <button className="btn-hover" style={{...s.btn("ghost"), marginBottom:24}} onClick={() => setView("admin")}><ArrowLeft size={14}/> Cancel</button>
    <div style={{fontFamily:"'Bebas Neue',sans-serif", fontSize:26, letterSpacing:2, color:"#C8952A", marginBottom:24}}>{editDoc ? "EDIT DOCUMENT" : "NEW DOCUMENT"}</div>
    <div style={s.formGroup}><label style={s.label}>Document Title *</label><input style={s.input} value={form.title} onChange={e => setForm(f => ({...f, title:e.target.value}))} placeholder="e.g. Opening Checklist — Prospect Park"/></div>
    <div style={{display:"grid", gridTemplateColumns:"1fr 1fr", gap:16, marginBottom:18}}><div><label style={s.label}>Category *</label><select style={{...s.input, cursor:"pointer"}} value={form.category} onChange={e => setForm(f => ({...f, category:e.target.value}))}>{CATEGORIES.map(c => <option key={c.id} value={c.id}>{c.label}</option>)}</select></div><div><label style={s.label}>Subcategory</label><input style={s.input} value={form.subcategory} onChange={e => setForm(f => ({...f, subcategory:e.target.value}))} placeholder="e.g. Daily Checklists"/></div></div>
    <div style={s.formGroup}><label style={s.label}>Tags (comma-separated)</label><input style={s.input} value={form.tags} onChange={e => setForm(f => ({...f, tags:e.target.value}))} placeholder="opening, checklist, FOH"/></div>
    <div style={s.formGroup}><label style={s.label}>Locations</label><div style={{display:"flex", flexWrap:"wrap", gap:8}}>{LOCATIONS.map(loc => <button key={loc} style={s.multiChip(form.locations.includes(loc))} onClick={() => toggleLocForm(loc)}>{loc}</button>)}</div></div>
    <div style={s.formGroup}><label style={s.label}>Audience / Roles</label><div style={{display:"flex", flexWrap:"wrap", gap:8}}>{ROLES.map(role => <button key={role} style={s.multiChip(form.roles.includes(role))} onClick={() => toggleRoleForm(role)}>{role}</button>)}</div></div>
    <div style={s.formGroup}><div style={{display:"flex", alignItems:"center", gap:10, marginBottom:6}}><label style={{...s.label, marginBottom:0}}>Featured?</label><input type="checkbox" checked={form.featured} onChange={e => setForm(f => ({...f, featured:e.target.checked}))} style={{width:16, height:16, cursor:"pointer"}}/><span style={{fontSize:12, color:"#666"}}>Shows in featured section on home</span></div></div>
    <div style={s.formGroup}><label style={s.label}>Attached File (PDF, Word, Image)</label><div style={{fontSize:11, color:"#555", marginBottom:8}}>Upload a file that staff can view or download. PDFs display inline. You can upload a file AND add text content below, or just one.</div>
      <input ref={fileInputRef} type="file" accept=".pdf,.doc,.docx,.xlsx,.xls,.pptx,.png,.jpg,.jpeg,.gif" style={{display:"none"}} onChange={e => { if (e.target.files[0]) { setPendingFile(e.target.files[0]); } }}/>
      <div style={{display:"flex", gap:10, alignItems:"center", flexWrap:"wrap"}}>
        <button type="button" className="btn-hover" style={s.btn("ghost")} onClick={() => fileInputRef.current?.click()}><Plus size={13}/> {pendingFile || form.fileURL ? "Replace File" : "Choose File"}</button>
        {pendingFile && <span style={{fontSize:13, color:"#5CB85C", fontWeight:600}}>{pendingFile.name} (ready to upload)</span>}
        {!pendingFile && form.fileURL && <span style={{fontSize:13, color:"#C8952A"}}>{form.fileName} (current)</span>}
        {(pendingFile || form.fileURL) && <button type="button" className="btn-hover" style={{...s.btn("ghost"), color:"#B03A2E", borderColor:"#B03A2E"}} onClick={() => { setPendingFile(null); setForm(f => ({...f, fileName:"", fileURL:"", fileType:""})); }}><X size={12}/> Remove</button>}
      </div>
    </div>
    <div style={s.formGroup}><label style={s.label}>Content (Markdown supported — optional if file attached)</label><div style={{fontSize:11, color:"#555", marginBottom:6}}>Use # ## ### for headers, **bold**, - for bullets, - [ ] for checkboxes</div><textarea style={s.textarea} value={form.content} onChange={e => setForm(f => ({...f, content:e.target.value}))} placeholder={"# Document Title\n\n## Section Header\n\nYour content here..."}/></div>
    <div style={{display:"flex", gap:12, alignItems:"center"}}>{uploading ? <div style={{color:"#C8952A", fontWeight:600, fontSize:14}}>Uploading file...</div> : <button className="btn-hover" style={{...s.btn("gold"), padding:"10px 28px", fontSize:14}} onClick={handleSave}><Save size={14}/> {editDoc ? "Save Changes" : "Publish Document"}</button>}<button className="btn-hover" style={s.btn("ghost")} onClick={() => { setPendingFile(null); setView("admin"); }}>Cancel</button>{saveMsg && <span style={{color:"#5CB85C", fontWeight:600, fontSize:13}}>{saveMsg}</span>}</div>
  </div>);

  return (
    <div style={s.wrap}>
      <style>{docCSS}</style>
      <Header/><FilterBar/>
      <div style={s.main}>
        {view === "home" && <HomeView/>}
        {view === "category" && <CategoryView/>}
        {view === "doc" && <DocView/>}
        {view === "search" && <SearchView/>}
        {view === "admin" && isAdmin && <AdminView/>}
        {view === "edit" && isAdmin && <EditView/>}
      </div>
      {showLogin && (<div style={s.modal} onClick={() => setShowLogin(false)}><div style={s.modalBox} onClick={e => e.stopPropagation()}><div style={{fontFamily:"'Bebas Neue',sans-serif", fontSize:22, letterSpacing:2, color:"#C8952A", marginBottom:4}}>ADMIN LOGIN</div><div style={{fontSize:13, color:"#666", marginBottom:20}}>Management & content administrators only.</div><input type="password" style={{...s.input, marginBottom:12}} placeholder="Enter admin password" value={pwInput} onChange={e => { setPwInput(e.target.value); setPwError(false); }} onKeyDown={e => e.key === "Enter" && handleLogin()} />{pwError && <div style={{color:"#B03A2E", fontSize:12, marginBottom:10}}>Incorrect password.</div>}<div style={{display:"flex", gap:10}}><button className="btn-hover" style={{...s.btn("gold"), flex:1}} onClick={handleLogin}><LogIn size={14}/> Login</button><button className="btn-hover" style={s.btn("ghost")} onClick={() => setShowLogin(false)}>Cancel</button></div></div></div>)}
      {deleteConfirm && (<div style={s.modal} onClick={() => setDeleteConfirm(null)}><div style={s.modalBox} onClick={e => e.stopPropagation()}><AlertTriangle size={24} color="#B03A2E" style={{marginBottom:12}}/><div style={{fontWeight:700, fontSize:16, marginBottom:8}}>Delete Document?</div><div style={{fontSize:13, color:"#888", marginBottom:20}}>"<strong style={{color:"#F7F5F0"}}>{deleteConfirm.title}</strong>" will be permanently removed.</div><div style={{display:"flex", gap:10}}><button className="btn-hover" style={{...s.btn("danger"), flex:1}} onClick={() => handleDelete(deleteConfirm.id)}><Trash2 size={13}/> Delete</button><button className="btn-hover" style={s.btn("ghost")} onClick={() => setDeleteConfirm(null)}>Cancel</button></div></div></div>)}
      {showRecipeLock && (<div style={s.modal} onClick={() => { setShowRecipeLock(false); setRecipeLockTarget(null); }}><div style={s.modalBox} onClick={e => e.stopPropagation()}><Lock size={24} color="#C8952A" style={{marginBottom:12}}/><div style={{fontFamily:"'Bebas Neue',sans-serif", fontSize:22, letterSpacing:2, color:"#C8952A", marginBottom:4}}>RECIPES LOCKED</div><div style={{fontSize:13, color:"#888", marginBottom:20}}>Recipe content is proprietary. Enter the recipe password to continue.</div><input type="password" style={{...s.input, marginBottom:12}} placeholder="Enter recipe password" value={recipePwInput} onChange={e => { setRecipePwInput(e.target.value); setRecipePwError(false); }} onKeyDown={e => e.key === "Enter" && handleRecipeUnlock()} />{recipePwError && <div style={{color:"#B03A2E", fontSize:12, marginBottom:10}}>Incorrect password.</div>}<div style={{display:"flex", gap:10}}><button className="btn-hover" style={{...s.btn("gold"), flex:1}} onClick={handleRecipeUnlock}><Lock size={14}/> Unlock Recipes</button><button className="btn-hover" style={s.btn("ghost")} onClick={() => { setShowRecipeLock(false); setRecipeLockTarget(null); }}>Cancel</button></div></div></div>)}
      {saveMsg && <div style={s.toast}>{saveMsg}</div>}
    </div>
  );
}
